// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnL52X3alUsX7OmAbEaZ0leoFL2GDc6d0',
    appId: '1:1076703021228:web:028da1a8a5e25775e33709',
    messagingSenderId: '1076703021228',
    projectId: 'food-order-app-b00aa',
    authDomain: 'food-order-app-b00aa.firebaseapp.com',
    storageBucket: 'food-order-app-b00aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFewNqLSSpJL1um8xlocSwSOCjRvwLNM0',
    appId: '1:1076703021228:android:e02444db6373dbd3e33709',
    messagingSenderId: '1076703021228',
    projectId: 'food-order-app-b00aa',
    storageBucket: 'food-order-app-b00aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3PHlKEwfBIDPkehLgkbbn_ejIYd0YKwg',
    appId: '1:1076703021228:ios:e3b30a0189020286e33709',
    messagingSenderId: '1076703021228',
    projectId: 'food-order-app-b00aa',
    storageBucket: 'food-order-app-b00aa.appspot.com',
    iosClientId: '1076703021228-enrdkcshmelhqmdc8dmtv1culf6k583e.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3PHlKEwfBIDPkehLgkbbn_ejIYd0YKwg',
    appId: '1:1076703021228:ios:e3b30a0189020286e33709',
    messagingSenderId: '1076703021228',
    projectId: 'food-order-app-b00aa',
    storageBucket: 'food-order-app-b00aa.appspot.com',
    iosClientId: '1076703021228-enrdkcshmelhqmdc8dmtv1culf6k583e.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderApp',
  );
}
